/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedTestCasesIndexRouteImport } from './routes/_authenticated.test-cases.index'
import { Route as AuthenticatedPersonasIndexRouteImport } from './routes/_authenticated.personas.index'
import { Route as AuthenticatedLeadPromptsIndexRouteImport } from './routes/_authenticated.lead-prompts.index'
import { Route as AuthenticatedPersonasIdRouteImport } from './routes/_authenticated.personas.$id'
import { Route as AuthenticatedLeadPromptsIdRouteImport } from './routes/_authenticated.lead-prompts.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestCasesIndexRoute =
  AuthenticatedTestCasesIndexRouteImport.update({
    id: '/test-cases/',
    path: '/test-cases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonasIndexRoute =
  AuthenticatedPersonasIndexRouteImport.update({
    id: '/personas/',
    path: '/personas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadPromptsIndexRoute =
  AuthenticatedLeadPromptsIndexRouteImport.update({
    id: '/lead-prompts/',
    path: '/lead-prompts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonasIdRoute = AuthenticatedPersonasIdRouteImport.update({
  id: '/personas/$id',
  path: '/personas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadPromptsIdRoute =
  AuthenticatedLeadPromptsIdRouteImport.update({
    id: '/lead-prompts/$id',
    path: '/lead-prompts/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/lead-prompts/$id': typeof AuthenticatedLeadPromptsIdRoute
  '/personas/$id': typeof AuthenticatedPersonasIdRoute
  '/lead-prompts/': typeof AuthenticatedLeadPromptsIndexRoute
  '/personas/': typeof AuthenticatedPersonasIndexRoute
  '/test-cases/': typeof AuthenticatedTestCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/lead-prompts/$id': typeof AuthenticatedLeadPromptsIdRoute
  '/personas/$id': typeof AuthenticatedPersonasIdRoute
  '/lead-prompts': typeof AuthenticatedLeadPromptsIndexRoute
  '/personas': typeof AuthenticatedPersonasIndexRoute
  '/test-cases': typeof AuthenticatedTestCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/lead-prompts/$id': typeof AuthenticatedLeadPromptsIdRoute
  '/_authenticated/personas/$id': typeof AuthenticatedPersonasIdRoute
  '/_authenticated/lead-prompts/': typeof AuthenticatedLeadPromptsIndexRoute
  '/_authenticated/personas/': typeof AuthenticatedPersonasIndexRoute
  '/_authenticated/test-cases/': typeof AuthenticatedTestCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/lead-prompts/$id'
    | '/personas/$id'
    | '/lead-prompts/'
    | '/personas/'
    | '/test-cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/lead-prompts/$id'
    | '/personas/$id'
    | '/lead-prompts'
    | '/personas'
    | '/test-cases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/lead-prompts/$id'
    | '/_authenticated/personas/$id'
    | '/_authenticated/lead-prompts/'
    | '/_authenticated/personas/'
    | '/_authenticated/test-cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-cases/': {
      id: '/_authenticated/test-cases/'
      path: '/test-cases'
      fullPath: '/test-cases/'
      preLoaderRoute: typeof AuthenticatedTestCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personas/': {
      id: '/_authenticated/personas/'
      path: '/personas'
      fullPath: '/personas/'
      preLoaderRoute: typeof AuthenticatedPersonasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lead-prompts/': {
      id: '/_authenticated/lead-prompts/'
      path: '/lead-prompts'
      fullPath: '/lead-prompts/'
      preLoaderRoute: typeof AuthenticatedLeadPromptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personas/$id': {
      id: '/_authenticated/personas/$id'
      path: '/personas/$id'
      fullPath: '/personas/$id'
      preLoaderRoute: typeof AuthenticatedPersonasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lead-prompts/$id': {
      id: '/_authenticated/lead-prompts/$id'
      path: '/lead-prompts/$id'
      fullPath: '/lead-prompts/$id'
      preLoaderRoute: typeof AuthenticatedLeadPromptsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLeadPromptsIdRoute: typeof AuthenticatedLeadPromptsIdRoute
  AuthenticatedPersonasIdRoute: typeof AuthenticatedPersonasIdRoute
  AuthenticatedLeadPromptsIndexRoute: typeof AuthenticatedLeadPromptsIndexRoute
  AuthenticatedPersonasIndexRoute: typeof AuthenticatedPersonasIndexRoute
  AuthenticatedTestCasesIndexRoute: typeof AuthenticatedTestCasesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLeadPromptsIdRoute: AuthenticatedLeadPromptsIdRoute,
  AuthenticatedPersonasIdRoute: AuthenticatedPersonasIdRoute,
  AuthenticatedLeadPromptsIndexRoute: AuthenticatedLeadPromptsIndexRoute,
  AuthenticatedPersonasIndexRoute: AuthenticatedPersonasIndexRoute,
  AuthenticatedTestCasesIndexRoute: AuthenticatedTestCasesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
